package webresources.Locations;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.catalina.User;
import org.hibernate.validator.constraints.Length;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Set;


@Entity
@Table(name = "locations")
public class LocationResource {
    // An autogenerated id (unique for each location in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long id;

    @NotNull
    @JsonProperty("name")
    public String name;

    @NotNull
    @JsonProperty("description")
    public String description;

    @NotNull
    @JsonProperty("latitude")
    public float  latitude;

    @NotNull
    @JsonProperty("longitude")
    public float longitude;

    @JsonProperty("image_url")
    public String image_url;

    @JsonProperty("votes")
    public int votes;

    @JsonProperty("createdBy")
    public long createdBy;

    @Column(name = "create_date")
    public java.sql.Timestamp createDate;

    @Column(name = "last_update_date")
    public java.sql.Timestamp lastUpdateDate;
}